insert into product (product_id, name, category) values (1, 'Aceite de girasol', 'Lácteos');
insert into product (product_id, name, category) values (2, 'Harina de maíz', 'Cereales');
insert into product (product_id, name, category) values (3, 'Aceite de canola', 'Dulces');
insert into product (product_id, name, category) values (4, 'Té', 'Lácteos');
insert into product (product_id, name, category) values (5, 'Tomate', 'Pescados');
insert into product (product_id, name, category) values (6, 'Jugo', 'Dulces');
insert into product (product_id, name, category) values (7, 'Harina de maíz', 'Aceites');
insert into product (product_id, name, category) values (8, 'Galletas', 'Carnes');
insert into product (product_id, name, category) values (9, 'Refresco', 'Bebidas');
insert into product (product_id, name, category) values (10, 'Sal', 'Condimentos');
insert into product (product_id, name, category) values (11, 'Arroz', 'Carnes');
insert into product (product_id, name, category) values (12, 'Trucha', 'Frutas y verduras');
insert into product (product_id, name, category) values (13, 'Pastel', 'Lácteos');
insert into product (product_id, name, category) values (14, 'Jugo', 'Frutas y verduras');
insert into product (product_id, name, category) values (15, 'Manzana', 'Condimentos');
insert into product (product_id, name, category) values (16, 'Carne de res', 'Dulces');
insert into product (product_id, name, category) values (17, 'Salmón', 'Condimentos');
insert into product (product_id, name, category) values (18, 'Harina de maíz', 'Carnes');
insert into product (product_id, name, category) values (19, 'Harina de avena', 'Pescados');
insert into product (product_id, name, category) values (20, 'Harina de maíz', 'Dulces');
insert into product (product_id, name, category) values (21, 'Cebolla', 'Carnes');
insert into product (product_id, name, category) values (22, 'Carne de res', 'Bebidas');
insert into product (product_id, name, category) values (23, 'Aceite de oliva', 'Dulces');
insert into product (product_id, name, category) values (24, 'Té', 'Carnes');
insert into product (product_id, name, category) values (25, 'Naranja', 'Carnes');
insert into product (product_id, name, category) values (26, 'Plátano', 'Cereales');
insert into product (product_id, name, category) values (27, 'Arroz', 'Dulces');
insert into product (product_id, name, category) values (28, 'Aceite de oliva', 'Lácteos');
insert into product (product_id, name, category) values (29, 'Carne de cerdo', 'Bebidas');
insert into product (product_id, name, category) values (30, 'Harina de maíz', 'Condimentos');
insert into product (product_id, name, category) values (31, 'Galletas', 'Aceites');
insert into product (product_id, name, category) values (32, 'Café', 'Carnes');
insert into product (product_id, name, category) values (33, 'Pastel', 'Dulces');
insert into product (product_id, name, category) values (34, 'Leche', 'Aceites');
insert into product (product_id, name, category) values (35, 'Arroz', 'Cereales');
insert into product (product_id, name, category) values (36, 'Trigo', 'Carnes');
insert into product (product_id, name, category) values (37, 'Salmón', 'Frutas y verduras');
insert into product (product_id, name, category) values (38, 'Té', 'Carnes');
insert into product (product_id, name, category) values (39, 'Galletas', 'Aceites');
insert into product (product_id, name, category) values (40, 'Plátano', 'Bebidas');
insert into product (product_id, name, category) values (41, 'Jugo', 'Condimentos');
insert into product (product_id, name, category) values (42, 'Queso', 'Carnes');
insert into product (product_id, name, category) values (43, 'Té', 'Carnes');
insert into product (product_id, name, category) values (44, 'Pimienta', 'Condimentos');
insert into product (product_id, name, category) values (45, 'Pastel', 'Aceites');
insert into product (product_id, name, category) values (46, 'Atún', 'Frutas y verduras');
insert into product (product_id, name, category) values (47, 'Chocolate', 'Cereales');
insert into product (product_id, name, category) values (48, 'Carne de cerdo', 'Cereales');
insert into product (product_id, name, category) values (49, 'Galletas', 'Pescados');
insert into product (product_id, name, category) values (50, 'Maíz', 'Aceites');
insert into product (product_id, name, category) values (51, 'Lechuga', 'Bebidas');
insert into product (product_id, name, category) values (52, 'Ajo', 'Harinas');
insert into product (product_id, name, category) values (53, 'Arroz', 'Frutas y verduras');
insert into product (product_id, name, category) values (54, 'Pimienta', 'Condimentos');
insert into product (product_id, name, category) values (55, 'Harina de avena', 'Dulces');
insert into product (product_id, name, category) values (56, 'Harina de maíz', 'Condimentos');
insert into product (product_id, name, category) values (57, 'Arroz', 'Cereales');
insert into product (product_id, name, category) values (58, 'Chocolate', 'Lácteos');
insert into product (product_id, name, category) values (59, 'Trucha', 'Bebidas');
insert into product (product_id, name, category) values (60, 'Tomate', 'Condimentos');
insert into product (product_id, name, category) values (61, 'Aceite de oliva', 'Carnes');
insert into product (product_id, name, category) values (62, 'Pastel', 'Carnes');
insert into product (product_id, name, category) values (63, 'Queso', 'Frutas y verduras');
insert into product (product_id, name, category) values (64, 'Carne de res', 'Condimentos');
insert into product (product_id, name, category) values (65, 'Sal', 'Aceites');
insert into product (product_id, name, category) values (66, 'Cebolla', 'Condimentos');
insert into product (product_id, name, category) values (67, 'Carne de res', 'Bebidas');
insert into product (product_id, name, category) values (68, 'Cebolla', 'Carnes');
insert into product (product_id, name, category) values (69, 'Té', 'Aceites');
insert into product (product_id, name, category) values (70, 'Arroz', 'Frutas y verduras');
insert into product (product_id, name, category) values (71, 'Naranja', 'Bebidas');
insert into product (product_id, name, category) values (72, 'Galletas', 'Harinas');
insert into product (product_id, name, category) values (73, 'Ajo', 'Lácteos');
insert into product (product_id, name, category) values (74, 'Yogur', 'Pescados');
insert into product (product_id, name, category) values (75, 'Atún', 'Bebidas');
insert into product (product_id, name, category) values (76, 'Café', 'Cereales');
insert into product (product_id, name, category) values (77, 'Sal', 'Harinas');
insert into product (product_id, name, category) values (78, 'Aceite de girasol', 'Pescados');
insert into product (product_id, name, category) values (79, 'Plátano', 'Condimentos');
insert into product (product_id, name, category) values (80, 'Plátano', 'Harinas');
insert into product (product_id, name, category) values (81, 'Leche', 'Bebidas');
insert into product (product_id, name, category) values (82, 'Lechuga', 'Lácteos');
insert into product (product_id, name, category) values (83, 'Carne de res', 'Cereales');
insert into product (product_id, name, category) values (84, 'Queso', 'Condimentos');
insert into product (product_id, name, category) values (85, 'Aceite de girasol', 'Harinas');
insert into product (product_id, name, category) values (86, 'Salmón', 'Pescados');
insert into product (product_id, name, category) values (87, 'Galletas', 'Frutas y verduras');
insert into product (product_id, name, category) values (88, 'Pimienta', 'Bebidas');
insert into product (product_id, name, category) values (89, 'Carne de cerdo', 'Frutas y verduras');
insert into product (product_id, name, category) values (90, 'Pimienta', 'Bebidas');
insert into product (product_id, name, category) values (91, 'Tomate', 'Condimentos');
insert into product (product_id, name, category) values (92, 'Cebolla', 'Carnes');
insert into product (product_id, name, category) values (93, 'Pimienta', 'Carnes');
insert into product (product_id, name, category) values (94, 'Jugo', 'Cereales');
insert into product (product_id, name, category) values (95, 'Pastel', 'Pescados');
insert into product (product_id, name, category) values (96, 'Leche', 'Aceites');
insert into product (product_id, name, category) values (97, 'Manzana', 'Frutas y verduras');
insert into product (product_id, name, category) values (98, 'Queso', 'Lácteos');
insert into product (product_id, name, category) values (99, 'Plátano', 'Lácteos');
insert into product (product_id, name, category) values (100, 'Pastel', 'Frutas y verduras');
insert into product (product_id, name, category) values (101, 'Lechuga', 'Pescados');
insert into product (product_id, name, category) values (102, 'Aceite de girasol', 'Harinas');
insert into product (product_id, name, category) values (103, 'Agua', 'Bebidas');
insert into product (product_id, name, category) values (104, 'Carne de res', 'Harinas');
insert into product (product_id, name, category) values (105, 'Aceite de girasol', 'Aceites');
insert into product (product_id, name, category) values (106, 'Cebolla', 'Dulces');
insert into product (product_id, name, category) values (107, 'Atún', 'Carnes');
insert into product (product_id, name, category) values (108, 'Sal', 'Frutas y verduras');
insert into product (product_id, name, category) values (109, 'Queso', 'Lácteos');
insert into product (product_id, name, category) values (110, 'Cebolla', 'Condimentos');
insert into product (product_id, name, category) values (111, 'Trigo', 'Cereales');
insert into product (product_id, name, category) values (112, 'Pimienta', 'Harinas');
insert into product (product_id, name, category) values (113, 'Arroz', 'Aceites');
insert into product (product_id, name, category) values (114, 'Aceite de canola', 'Frutas y verduras');
insert into product (product_id, name, category) values (115, 'Agua', 'Aceites');
insert into product (product_id, name, category) values (116, 'Plátano', 'Lácteos');
insert into product (product_id, name, category) values (117, 'Trigo', 'Pescados');
insert into product (product_id, name, category) values (118, 'Té', 'Cereales');
insert into product (product_id, name, category) values (119, 'Sal', 'Carnes');
insert into product (product_id, name, category) values (120, 'Harina de maíz', 'Condimentos');
insert into product (product_id, name, category) values (121, 'Aceite de oliva', 'Carnes');
insert into product (product_id, name, category) values (122, 'Ajo', 'Lácteos');
insert into product (product_id, name, category) values (123, 'Aceite de oliva', 'Cereales');
insert into product (product_id, name, category) values (124, 'Naranja', 'Aceites');
insert into product (product_id, name, category) values (125, 'Refresco', 'Condimentos');
insert into product (product_id, name, category) values (126, 'Aceite de canola', 'Condimentos');
insert into product (product_id, name, category) values (127, 'Manzana', 'Condimentos');
insert into product (product_id, name, category) values (128, 'Carne de cerdo', 'Carnes');
insert into product (product_id, name, category) values (129, 'Carne de res', 'Frutas y verduras');
insert into product (product_id, name, category) values (130, 'Aceite de girasol', 'Bebidas');
insert into product (product_id, name, category) values (131, 'Chocolate', 'Cereales');
insert into product (product_id, name, category) values (132, 'Trucha', 'Bebidas');
insert into product (product_id, name, category) values (133, 'Carne de cerdo', 'Pescados');
insert into product (product_id, name, category) values (134, 'Naranja', 'Dulces');
insert into product (product_id, name, category) values (135, 'Leche', 'Carnes');
insert into product (product_id, name, category) values (136, 'Plátano', 'Harinas');
insert into product (product_id, name, category) values (137, 'Harina de trigo', 'Carnes');
insert into product (product_id, name, category) values (138, 'Ajo', 'Harinas');
insert into product (product_id, name, category) values (139, 'Sal', 'Dulces');
insert into product (product_id, name, category) values (140, 'Aceite de girasol', 'Cereales');
insert into product (product_id, name, category) values (141, 'Yogur', 'Dulces');
insert into product (product_id, name, category) values (142, 'Queso', 'Aceites');
insert into product (product_id, name, category) values (143, 'Plátano', 'Bebidas');
insert into product (product_id, name, category) values (144, 'Harina de trigo', 'Harinas');
insert into product (product_id, name, category) values (145, 'Pollo', 'Frutas y verduras');
insert into product (product_id, name, category) values (146, 'Café', 'Carnes');
insert into product (product_id, name, category) values (147, 'Lechuga', 'Carnes');
insert into product (product_id, name, category) values (148, 'Lechuga', 'Aceites');
insert into product (product_id, name, category) values (149, 'Harina de avena', 'Pescados');
insert into product (product_id, name, category) values (150, 'Carne de res', 'Carnes');
insert into product (product_id, name, category) values (151, 'Harina de trigo', 'Harinas');
insert into product (product_id, name, category) values (152, 'Harina de trigo', 'Lácteos');
insert into product (product_id, name, category) values (153, 'Yogur', 'Lácteos');
insert into product (product_id, name, category) values (154, 'Ajo', 'Cereales');
insert into product (product_id, name, category) values (155, 'Harina de avena', 'Condimentos');
insert into product (product_id, name, category) values (156, 'Lechuga', 'Aceites');
insert into product (product_id, name, category) values (157, 'Pastel', 'Bebidas');
insert into product (product_id, name, category) values (158, 'Carne de res', 'Frutas y verduras');
insert into product (product_id, name, category) values (159, 'Carne de res', 'Frutas y verduras');
insert into product (product_id, name, category) values (160, 'Jugo', 'Harinas');
insert into product (product_id, name, category) values (161, 'Aceite de oliva', 'Pescados');
insert into product (product_id, name, category) values (162, 'Trigo', 'Harinas');
insert into product (product_id, name, category) values (163, 'Jugo', 'Cereales');
insert into product (product_id, name, category) values (164, 'Refresco', 'Carnes');
insert into product (product_id, name, category) values (165, 'Atún', 'Condimentos');
insert into product (product_id, name, category) values (166, 'Galletas', 'Lácteos');
insert into product (product_id, name, category) values (167, 'Leche', 'Dulces');
insert into product (product_id, name, category) values (168, 'Harina de avena', 'Lácteos');
insert into product (product_id, name, category) values (169, 'Cebolla', 'Carnes');
insert into product (product_id, name, category) values (170, 'Harina de avena', 'Frutas y verduras');
insert into product (product_id, name, category) values (171, 'Sal', 'Bebidas');
insert into product (product_id, name, category) values (172, 'Carne de res', 'Frutas y verduras');
insert into product (product_id, name, category) values (173, 'Queso', 'Cereales');
insert into product (product_id, name, category) values (174, 'Queso', 'Dulces');
insert into product (product_id, name, category) values (175, 'Tomate', 'Condimentos');
insert into product (product_id, name, category) values (176, 'Pimienta', 'Dulces');
insert into product (product_id, name, category) values (177, 'Plátano', 'Aceites');
insert into product (product_id, name, category) values (178, 'Plátano', 'Lácteos');
insert into product (product_id, name, category) values (179, 'Lechuga', 'Harinas');
insert into product (product_id, name, category) values (180, 'Plátano', 'Dulces');
insert into product (product_id, name, category) values (181, 'Trigo', 'Lácteos');
insert into product (product_id, name, category) values (182, 'Ajo', 'Harinas');
insert into product (product_id, name, category) values (183, 'Aceite de girasol', 'Condimentos');
insert into product (product_id, name, category) values (184, 'Té', 'Pescados');
insert into product (product_id, name, category) values (185, 'Café', 'Carnes');
insert into product (product_id, name, category) values (186, 'Salmón', 'Aceites');
insert into product (product_id, name, category) values (187, 'Salmón', 'Aceites');
insert into product (product_id, name, category) values (188, 'Maíz', 'Cereales');
insert into product (product_id, name, category) values (189, 'Lechuga', 'Condimentos');
insert into product (product_id, name, category) values (190, 'Leche', 'Aceites');
insert into product (product_id, name, category) values (191, 'Plátano', 'Cereales');
insert into product (product_id, name, category) values (192, 'Aceite de oliva', 'Condimentos');
insert into product (product_id, name, category) values (193, 'Pastel', 'Harinas');
insert into product (product_id, name, category) values (194, 'Queso', 'Harinas');
insert into product (product_id, name, category) values (195, 'Aceite de canola', 'Pescados');
insert into product (product_id, name, category) values (196, 'Trucha', 'Lácteos');
insert into product (product_id, name, category) values (197, 'Agua', 'Dulces');
insert into product (product_id, name, category) values (198, 'Plátano', 'Bebidas');
insert into product (product_id, name, category) values (199, 'Leche', 'Bebidas');
insert into product (product_id, name, category) values (200, 'Pastel', 'Pescados');
insert into product (product_id, name, category) values (201, 'Pimienta', 'Condimentos');
insert into product (product_id, name, category) values (202, 'Yogur', 'Pescados');
insert into product (product_id, name, category) values (203, 'Manzana', 'Frutas y verduras');
insert into product (product_id, name, category) values (204, 'Queso', 'Pescados');
insert into product (product_id, name, category) values (205, 'Jugo', 'Frutas y verduras');
insert into product (product_id, name, category) values (206, 'Harina de trigo', 'Lácteos');
insert into product (product_id, name, category) values (207, 'Cebolla', 'Frutas y verduras');
insert into product (product_id, name, category) values (208, 'Café', 'Lácteos');
insert into product (product_id, name, category) values (209, 'Café', 'Cereales');
insert into product (product_id, name, category) values (210, 'Agua', 'Harinas');
insert into product (product_id, name, category) values (211, 'Pastel', 'Aceites');
insert into product (product_id, name, category) values (212, 'Manzana', 'Lácteos');
insert into product (product_id, name, category) values (213, 'Té', 'Harinas');
insert into product (product_id, name, category) values (214, 'Harina de maíz', 'Carnes');
insert into product (product_id, name, category) values (215, 'Lechuga', 'Dulces');
insert into product (product_id, name, category) values (216, 'Naranja', 'Condimentos');
insert into product (product_id, name, category) values (217, 'Cebolla', 'Aceites');
insert into product (product_id, name, category) values (218, 'Refresco', 'Carnes');
insert into product (product_id, name, category) values (219, 'Refresco', 'Frutas y verduras');
insert into product (product_id, name, category) values (220, 'Manzana', 'Cereales');
insert into product (product_id, name, category) values (221, 'Pollo', 'Harinas');
insert into product (product_id, name, category) values (222, 'Naranja', 'Carnes');
insert into product (product_id, name, category) values (223, 'Harina de avena', 'Dulces');
insert into product (product_id, name, category) values (224, 'Naranja', 'Condimentos');
insert into product (product_id, name, category) values (225, 'Trucha', 'Harinas');
insert into product (product_id, name, category) values (226, 'Tomate', 'Cereales');
insert into product (product_id, name, category) values (227, 'Pastel', 'Frutas y verduras');
insert into product (product_id, name, category) values (228, 'Refresco', 'Harinas');
insert into product (product_id, name, category) values (229, 'Refresco', 'Frutas y verduras');
insert into product (product_id, name, category) values (230, 'Naranja', 'Harinas');
insert into product (product_id, name, category) values (231, 'Salmón', 'Lácteos');
insert into product (product_id, name, category) values (232, 'Jugo', 'Aceites');
insert into product (product_id, name, category) values (233, 'Manzana', 'Aceites');
insert into product (product_id, name, category) values (234, 'Queso', 'Dulces');
insert into product (product_id, name, category) values (235, 'Trigo', 'Harinas');
insert into product (product_id, name, category) values (236, 'Trucha', 'Condimentos');
insert into product (product_id, name, category) values (237, 'Jugo', 'Condimentos');
insert into product (product_id, name, category) values (238, 'Ajo', 'Pescados');
insert into product (product_id, name, category) values (239, 'Jugo', 'Frutas y verduras');
insert into product (product_id, name, category) values (240, 'Aceite de oliva', 'Harinas');
insert into product (product_id, name, category) values (241, 'Cebolla', 'Pescados');
insert into product (product_id, name, category) values (242, 'Agua', 'Pescados');
insert into product (product_id, name, category) values (243, 'Yogur', 'Dulces');
insert into product (product_id, name, category) values (244, 'Tomate', 'Harinas');
insert into product (product_id, name, category) values (245, 'Manzana', 'Condimentos');
insert into product (product_id, name, category) values (246, 'Carne de res', 'Frutas y verduras');
insert into product (product_id, name, category) values (247, 'Cebolla', 'Lácteos');
insert into product (product_id, name, category) values (248, 'Carne de res', 'Dulces');
insert into product (product_id, name, category) values (249, 'Carne de cerdo', 'Lácteos');
insert into product (product_id, name, category) values (250, 'Trigo', 'Cereales');
insert into product (product_id, name, category) values (251, 'Ajo', 'Dulces');
insert into product (product_id, name, category) values (252, 'Trigo', 'Carnes');
insert into product (product_id, name, category) values (253, 'Carne de res', 'Dulces');
insert into product (product_id, name, category) values (254, 'Maíz', 'Frutas y verduras');
insert into product (product_id, name, category) values (255, 'Té', 'Condimentos');
insert into product (product_id, name, category) values (256, 'Harina de avena', 'Harinas');
insert into product (product_id, name, category) values (257, 'Maíz', 'Lácteos');
insert into product (product_id, name, category) values (258, 'Refresco', 'Dulces');
insert into product (product_id, name, category) values (259, 'Queso', 'Aceites');
insert into product (product_id, name, category) values (260, 'Pimienta', 'Lácteos');
insert into product (product_id, name, category) values (261, 'Aceite de oliva', 'Cereales');
insert into product (product_id, name, category) values (262, 'Pastel', 'Frutas y verduras');
insert into product (product_id, name, category) values (263, 'Harina de avena', 'Condimentos');
insert into product (product_id, name, category) values (264, 'Agua', 'Bebidas');
insert into product (product_id, name, category) values (265, 'Sal', 'Lácteos');
insert into product (product_id, name, category) values (266, 'Galletas', 'Harinas');
insert into product (product_id, name, category) values (267, 'Carne de cerdo', 'Pescados');
insert into product (product_id, name, category) values (268, 'Aceite de canola', 'Lácteos');
insert into product (product_id, name, category) values (269, 'Salmón', 'Dulces');
insert into product (product_id, name, category) values (270, 'Aceite de oliva', 'Bebidas');
insert into product (product_id, name, category) values (271, 'Carne de res', 'Harinas');
insert into product (product_id, name, category) values (272, 'Harina de maíz', 'Condimentos');
insert into product (product_id, name, category) values (273, 'Café', 'Frutas y verduras');
insert into product (product_id, name, category) values (274, 'Jugo', 'Aceites');
insert into product (product_id, name, category) values (275, 'Té', 'Aceites');
insert into product (product_id, name, category) values (276, 'Harina de maíz', 'Harinas');
insert into product (product_id, name, category) values (277, 'Galletas', 'Carnes');
insert into product (product_id, name, category) values (278, 'Harina de avena', 'Harinas');
insert into product (product_id, name, category) values (279, 'Arroz', 'Condimentos');
insert into product (product_id, name, category) values (280, 'Arroz', 'Dulces');
insert into product (product_id, name, category) values (281, 'Cebolla', 'Pescados');
insert into product (product_id, name, category) values (282, 'Pimienta', 'Aceites');
insert into product (product_id, name, category) values (283, 'Manzana', 'Carnes');
insert into product (product_id, name, category) values (284, 'Harina de trigo', 'Bebidas');
insert into product (product_id, name, category) values (285, 'Trucha', 'Carnes');
insert into product (product_id, name, category) values (286, 'Aceite de girasol', 'Harinas');
insert into product (product_id, name, category) values (287, 'Tomate', 'Bebidas');
insert into product (product_id, name, category) values (288, 'Leche', 'Harinas');
insert into product (product_id, name, category) values (289, 'Arroz', 'Pescados');
insert into product (product_id, name, category) values (290, 'Harina de avena', 'Frutas y verduras');
insert into product (product_id, name, category) values (291, 'Lechuga', 'Harinas');
insert into product (product_id, name, category) values (292, 'Pimienta', 'Harinas');
insert into product (product_id, name, category) values (293, 'Cebolla', 'Carnes');
insert into product (product_id, name, category) values (294, 'Chocolate', 'Lácteos');
insert into product (product_id, name, category) values (295, 'Pastel', 'Dulces');
insert into product (product_id, name, category) values (296, 'Carne de cerdo', 'Bebidas');
insert into product (product_id, name, category) values (297, 'Atún', 'Condimentos');
insert into product (product_id, name, category) values (298, 'Lechuga', 'Lácteos');
insert into product (product_id, name, category) values (299, 'Aceite de oliva', 'Carnes');
insert into product (product_id, name, category) values (300, 'Harina de maíz', 'Carnes');
