insert into supplier (nit_supplier, name, company, address, phone, email) values (1, 'Moyra', 'Pixope', '8 Boyd Avenue', 9543976, 'mgorham0@youtube.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (2, 'Orv', 'Yozio', '207 Homewood Crossing', 9467487, 'ohedditeh1@behance.net');
insert into supplier (nit_supplier, name, company, address, phone, email) values (3, 'Jackqueline', 'InnoZ', '26231 Brickson Park Lane', 3057420, 'jfebry2@histats.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (4, 'Ezequiel', 'Vinder', '55992 Saint Paul Road', 4948205, 'estive3@admin.ch');
insert into supplier (nit_supplier, name, company, address, phone, email) values (5, 'Jaquenetta', 'Youbridge', '10 Dottie Lane', 9487427, 'jlamdin4@buzzfeed.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (6, 'Luciana', 'Avamba', '544 Weeping Birch Plaza', 1287405, 'lsizeland5@weibo.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (7, 'Lyndsie', 'Zoovu', '75 Warrior Way', 4226819, 'lrawsthorne6@godaddy.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (8, 'Elana', 'Zoomlounge', '23631 Marcy Parkway', 9463330, 'efeldhuhn7@a8.net');
insert into supplier (nit_supplier, name, company, address, phone, email) values (9, 'Jobie', 'Agimba', '9404 Johnson Alley', 3048067, 'jgatheridge8@wired.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (10, 'Roseanne', 'Voonder', '84 Golden Leaf Place', 9057233, 'rulyat9@msn.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (11, 'Coreen', 'Agivu', '51542 Blaine Road', 4989114, 'cmacarthura@yelp.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (12, 'Maye', 'Photojam', '39281 Columbus Point', 3028941, 'mmcconigalb@army.mil');
insert into supplier (nit_supplier, name, company, address, phone, email) values (13, 'Matty', 'Izio', '870 Tomscot Drive', 3624159, 'mhovyc@ycombinator.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (14, 'Twyla', 'Twitterwire', '1469 Harbort Park', 4764393, 'talmakd@whitehouse.gov');
insert into supplier (nit_supplier, name, company, address, phone, email) values (15, 'Erie', 'Zoomcast', '6636 Badeau Terrace', 3212128, 'epevsnere@cpanel.net');
insert into supplier (nit_supplier, name, company, address, phone, email) values (16, 'Corissa', 'Kanoodle', '93766 Lawn Center', 8137508, 'cduddyf@army.mil');
insert into supplier (nit_supplier, name, company, address, phone, email) values (17, 'Murdock', 'Voonte', '7 Steensland Court', 4069825, 'mbenthamg@cdbaby.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (18, 'Emili', 'Kanoodle', '20103 Service Junction', 1760778, 'ebestwickh@abc.net.au');
insert into supplier (nit_supplier, name, company, address, phone, email) values (19, 'Tailor', 'Twitterlist', '6 Thackeray Lane', 7996527, 'trochelli@bloglovin.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (20, 'Inez', 'Flashpoint', '24 Reindahl Junction', 8497035, 'ipicklessj@imdb.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (21, 'Mollie', 'Kwilith', '90 Lotheville Parkway', 3916664, 'mkennak@youtube.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (22, 'Annice', 'Katz', '399 Oneill Way', 3744366, 'adunstonl@facebook.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (23, 'Tynan', 'Zoonder', '2 Mockingbird Alley', 3728504, 'tstanmanm@yandex.ru');
insert into supplier (nit_supplier, name, company, address, phone, email) values (24, 'Doralin', 'Jaxnation', '2 Kings Drive', 2154535, 'delhamn@usgs.gov');
insert into supplier (nit_supplier, name, company, address, phone, email) values (25, 'Paddie', 'Edgeify', '1658 Moulton Hill', 7486132, 'pferenso@house.gov');
insert into supplier (nit_supplier, name, company, address, phone, email) values (26, 'Cloris', 'Trilia', '1 Melby Point', 2760345, 'cpirrip@printfriendly.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (27, 'Flossi', 'Demizz', '9955 Carioca Trail', 6567957, 'fstrobanq@ning.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (28, 'Frederick', 'Geba', '21059 Thompson Road', 6714690, 'fjessupr@elegantthemes.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (29, 'Ethyl', 'Midel', '8 Fieldstone Circle', 5311069, 'eadamowitzs@prnewswire.com');
insert into supplier (nit_supplier, name, company, address, phone, email) values (30, 'Isaac', 'Feedmix', '01 Golf View Alley', 5591003, 'iralfet@uol.com.br');
