version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=platzi
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80

# docker-compose up -d postgres
# docker-compose ps
# docker-compose down
